### ISSUE TITLE
 ModuleNotFoundError: No module named 'scripts.physton_prompt'

### ISSUE THREAD

**Issue by jason571** [Physton/sd-webui-prompt-all-in-one-app#6]
在stable-diffusion-webui中使用，本地scripts.physton_prompt.storage提示找不到，在scripts目录有多个module 会出现这个问题
尝试在on_app_started.py中增加下面路径也不能解决，求解
使用在WSL2

import sys
sys.path.append('/mnt/p/home/flyang/stable-diffusion-webui/extensions/sd-webui-prompt-all-in-one/scripts/physton_prompt')

*** Error loading script: on_app_started.py
    Traceback (most recent call last):
      File "/mnt/p/home/flyang/stable-diffusion-webui/modules/scripts.py", line 381, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/mnt/p/home/flyang/stable-diffusion-webui/modules/script_loading.py", line 12, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/mnt/p/home/flyang/stable-diffusion-webui/extensions/sd-webui-prompt-all-in-one/scripts/on_app_started.py", line 10, in <module>
        from scripts.physton_prompt.storage import Storage
    ModuleNotFoundError: No module named 'scripts.physton_prompt'

**Comment by Physton** [comment]
尝试在 `scripts/physton_prompt` 文件夹中创建一个空文件：`__init__.py`，看能否解决。
