### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 1972: illegal multibyte sequence

### ISSUE THREAD

**Issue by halfknife** [Physton/sd-webui-prompt-all-in-one-app#7]
![image](https://github.com/Physton/sd-webui-prompt-all-in-one-app/assets/160566244/15cf0d42-53d3-4963-ab20-6b2f7ceafd20)

Traceback (most recent call last):
  File "D:\sd-webui-prompt-all-in-one-app\app.py", line 9, in <module>
  `import gradio as gr`
  File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\__init__.py", line 3, in <module>
    `import gradio._simple_templates`
  File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    `from .simpledropdown import SimpleDropdown`
  File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    `from gradio.components.base import FormComponent`
  File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\components\__init__.py", line 40, in <module>
    `from gradio.components.multimodal_textbox import MultimodalTextbox`
  File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\components\multimodal_textbox.py", line 28, in <module>
    `class MultimodalTextbox(FormComponent):`
  File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\component_meta.py", line 198, in __new__
    `create_or_modify_pyi(component_class, name, events)`
  File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi
    `source_code = source_file.read_text()`
  File "C:\Users\win10\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1135, in read_text
    `return f.read()`
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 1972: illegal multibyte sequence

**Comment by xwxxwk** [comment]
Gradio的问题,看起来一时修不好的.

可以先手动将Python310\lib\site-packages\gradio\component_meta.py文件中的read_text()替换为read_text(encoding="utf-8")

我目前用着没问题.
